# Generated by Django 5.1.6 on 2025-03-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flash',
            new_name='FlashCard',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='medal',
            new_name='progress',
        ),
    ]
