# Generated by Django 5.1.6 on 2025-03-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_rename_flash_flashcard_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCard',
            new_name='Flash',
        ),
    ]
