[build]
cmd = '''buf generate && go build -o ./tmp/main cmd/main.go'''
bin = "./tmp/main"
include_ext = ["go", "templ", "proto"]
exclude_regex = ["_templ.go", ".pb.go", ".connect.go", "node_modules/.*"]

[log]
main_only = true
log_only_main_loop = true

delay = 1000
